### ISSUE TITLE
Cannot find module 'pg-native'

### ISSUE THREAD

**Issue by tahv0** [andywer/pg-listen#15]
Getting this warning message when importing the package with commonjs

`const createPostgresSubscriber = require('pg-listen')`

Getting console message: `Cannot find module 'pg-native'`

Everything seems to be working though. Maybe some problem in dependencies?

Using version pg-listen@1.2.0

**Comment by andywer** [comment]
Hey @tahv0!

Have you set the `native` option? (https://github.com/andywer/pg-listen/blob/816fde6d2eafe5f5055e46b3bd7e9aeb0f23225d/src/index.ts#L35)

If so, you will also need the pg-native dependency.

**Comment by tahv0** [comment]
> Hey @tahv0!
> 
> Have you set the `native` option? (
> 
> [pg-listen/src/index.ts](https://github.com/andywer/pg-listen/blob/816fde6d2eafe5f5055e46b3bd7e9aeb0f23225d/src/index.ts#L35)
> 
> Line 35 in [816fde6](/andywer/pg-listen/commit/816fde6d2eafe5f5055e46b3bd7e9aeb0f23225d)
> 
>  export interface Options { 
> )
> If so, you will also need the pg-native dependency.

No, I have not. I looked source code and it should default to false.  I tried to set that true and same effect.

**Comment by andywer** [comment]
I fear there is too little information to debug it from here.

You can try the following, though:
- Set the `native` option explicitly to `false`
- Grep for `native` in your project and check what it finds

**Comment by andywer** [comment]
Can you find any time to look into this?

Have a nice weekend!

**Comment by devilesk** [comment]
I'm having the same issue as well by doing `npm install pg pg-listen` in an empty directory and creating a test file with just `require('pg-listen')` in it.

**Comment by ekifox** [comment]
+1 here

const subscriber = createSubscriber({
  connectionString: process.env.POSTGRES_URL
}, {
  native: false
})

====> Cannot find module 'pg-native'

**Comment by andywer** [comment]
Haha, I think I found it!

Seems to be a rather widespread issue with `pg`: See <https://github.com/sequelize/sequelize/issues/3781#issuecomment-104278869>.

I suspect this line to trigger it: <https://github.com/andywer/pg-listen/blob/master/src/index.ts#L72>

Will have a look at it later today and release a patch!

**Comment by andywer** [comment]
Fix is published as v1.2.1 🚀

**Comment by damianobarbati** [comment]
Is this really fixed? I'm still seeing this in v5.8.5 (node v11.15.0): 

```
Cannot find module 'pg-native'
Require stack:
- /Users/damz/Desktop/setabeautyhome/node_modules/pg/lib/native/client.js
- /Users/damz/Desktop/setabeautyhome/node_modules/pg/lib/native/index.js
- /Users/damz/Desktop/setabeautyhome/node_modules/pg/lib/index.js
```

**Comment by andywer** [comment]
@damianobarbati `v5.8.5` of what? The `pg-listen` version would be important to know 😉

Btw, are you sure that this is not caused by some other code? I don't see any hint about `pg-listen` in the stack trace.

**Comment by damianobarbati** [comment]
Ops! @andywer sorry, I was sure to be in sequelize repo... ignore this 🤦🏻‍♂️
