### ISSUE TITLE
Incorrect processing of notifications without payload

### ISSUE THREAD

**Issue by KSDaemon** [andywer/pg-listen#24]
Hi! 

If an app receives an empty notification, done like this (without payload)
```sql
NOTIFY "channel";
```

Then, it crashes with:
```sh
Fatal database connection error: SyntaxError: Error parsing PostgreSQL notification payload: Unexpected end of JSON input
```

I think, the problem is here:
```js
payload = notification.payload !== undefined ? parse(notification.payload) : undefined
```
As `notification.payload` is an empty string in this case.

Can be fixed with this or similiar check:
```js
payload = notification.payload !== undefined || notification.payload !== '' ? parse(notification.payload) : undefined
```

**Comment by KSDaemon** [comment]
A workaround is to provide custom parse function, but i think it is no an optimal option for this case.

**Comment by andywer** [comment]
True. Thanks for reporting!

I think we should explicitly check for an empty string and resolve it to `undefined`. What do you think? Mind opening a PR?

**Comment by KSDaemon** [comment]
Well, why not. Just doing as I mentioned?

**Comment by andywer** [comment]
I think we can even simplify to
```js
payload = notification.payload ? parse(notification.payload) : undefined
```

**Comment by KSDaemon** [comment]
yep! Great! 
Do you really want me to PR this simple fix? Or you can just do it in 1 min by yourself? :)

**Comment by andywer** [comment]
Can do it, but probably not today. Packed with work right now.

But of course I can do it. Just wasn't sure how urgent it is to you 😉

**Comment by KSDaemon** [comment]
Ough, np! 
I'm also AFK for today.

**Comment by kwakwaversal** [comment]
Great stuff, thanks for fixing @andywer as I was just about to report this same issue. 👍 

As an addendum the [PostgreSQL docs](https://www.postgresql.org/docs/11/sql-notify.html) for notify says

> The information passed to the client for a notification event includes the notification channel name, the notifying session's server process PID, and the payload string, which is an empty string if it has not been specified.

So an explicit check for `''` _might_ be the right thing to do here as that's the guaranteed contract from pg, but a truthy check on a string will always return what you want. Potato potato. :)

Anyhoo, nice one!
