### ISSUE TITLE
Add a "connected" event.

### ISSUE THREAD

**Issue by laino** [andywer/pg-listen#26]
It's often that you need to perform some work to get back into a consistent state after losing your connection or after the initial connection is established (because you don't know what happened with the DB in the meantime). 

The ``reconnect`` *kinda* works for this, but it's emitted before the connection comes back.

It would be nice to have a general ``connect[ed]``/``reconnected`` event for this.

**Comment by andywer** [comment]
Hey @laino!

Yeah, that's a good point. Let's keep the `reconnect` event as it is and add a `connected` event.
Does that sound good to you?

**Comment by laino** [comment]
That would be great!

**Comment by andywer** [comment]
Published a pre-release. Would you like to give it a try?

Install via `npm i pg-listen@1.3.2-connected`. Find the PR with updated docs here: #27.

**Comment by laino** [comment]
@andywer It would probably be better to emit "connected" after everything is resubscribed, to avoid the user managing to fetch the most recent state before he's subscribed and thus missing some in-between updates.

**Comment by andywer** [comment]
Right! How about https://github.com/andywer/pg-listen/pull/27/commits/df673914b8aa48373d3df6e25d7f2517ac6fe5e5?

**Comment by laino** [comment]
Looks good. Thanks a lot! I'll try this soon.

I was just checking for this particular feature while evaluating libraries that might solve my particular problem, so haven't something to test this with yet.

**Comment by rhyek** [comment]
@laino is this included in 1.4.0?
