### ISSUE TITLE
Make Subscriber interface generic

### ISSUE THREAD

**Issue by rhyek** [andywer/pg-listen#28]
Make `Subsrciber` interface generic such that I can define custom notification events + payload types like so:
```ts
interface NotificationEvents {
  'inserted-row': {
    tableName: string;
    row: Record;
  };
}

export default class PgListenerService extends BaseService {
  subscriber: Subscriber<NotificationEvents>;

  constructor() {
    super();
    this.subscriber = createSubscriber({ connectionString: envs.pgDbUrl });
    process.on('exit', () => {
      this.subscriber.close();
    });
  }

  async init() {
    this.subscriber.notifications.on('inserted-row', payload => {
      payload.tableName; // string instead of any
    });
    await this.subscriber.connect();
    await this.subscriber.listenTo('inserted-row');
  }
}

```

**Comment by andywer** [comment]
Wow, I had to double-check that it really isn’t generic yet... Don’t ask me why it’s not. Let’s fix it 👍

**Comment by andywer** [comment]
Check out the pull request #29 😉

**Comment by rhyek** [comment]
It looks pretty slick. Any chance it being published today? Would like to use it for something I'm currently working on. 😁

**Comment by andywer** [comment]
Here we go: [v1.5.0](https://github.com/andywer/pg-listen/releases/tag/v1.5.0) 🚀

**Comment by rhyek** [comment]
@andywer, it works perfectly. Thank you very much and keep up the great work.
