### ISSUE TITLE
Where to pass options

### ISSUE THREAD

**Issue by nerdbaggy** [andywer/pg-listen#34]
Hello,
I need to change the retryTimeout but I can't figure out where to pass the options parameter. For the subscriber interface the connect function doesn't take the options parameters so I am not sure how to pass them.

Thanks!

**Comment by andywer** [comment]
Hey @nerdbaggy!

The default export of the package is the `createSubscriber` function. Pass the postgres connection config to it as the first argument and optionally advanced options (that’s what you are looking for) as the second argument.

See <https://github.com/andywer/pg-listen/blob/master/dist/index.d.ts> 😉
