### ISSUE TITLE
subscriber.notify() example is missing the channel

### ISSUE THREAD

**Issue by Finwood** [andywer/pg-listen#35]
The call to `subscriber.notify()` in the README's example is missing the channel argument.
To go with the example provided, it should rather look like this:
```js
export async function sendSampleMessage () {
  await subscriber.notify("my-channel", {
    greeting: "Hey, buddy.",
    timestamp: Date.now()
  })
}
```

**Comment by andywer** [comment]
Thanks for pointing out, @Finwood! 🙌
