### ISSUE TITLE
Does anyone have a nodejs example?

### ISSUE THREAD

**Issue by pnunn** [andywer/pg-listen#39]
Hi Guys,

just trying to get a really simple nodejs app running that just listens for notifications, prints the payloads and sits waiting for the next one.

I'm buggered if I can work out how to make this happen with pg-listen, it just drops straight through, obviously my lack of knowledge, but can anyone help out?

Ta.

**Comment by andywer** [comment]
Hey @pnunn! You can check out the [integration tests](https://github.com/andywer/pg-listen/blob/master/test/integration.test.ts) as a starting point.
