### ISSUE TITLE
Integration with node-postgres

### ISSUE THREAD

**Issue by ekifox** [andywer/pg-listen#4]
I want to pass to options not a connection string, I want to pass node-pg instance. May you can do update with parsing connection string from node-pg module instance?

**Comment by andywer** [comment]
Hey @ekifox! You should be able to pass the same connection options object to `createPostgresSubscriber()` that you would pass to `pg` directly.

Will update the docs to make that clearer. Tell me if you have any other feedback :)

**Comment by andywer** [comment]
Readme has been quick-fixed.
