### ISSUE TITLE
Channel with hyphen does not work

### ISSUE THREAD

**Issue by overmike** [andywer/pg-listen#53]
I tried using psql and listen the channel example 'my-channel'; 

```
# listen my-channel;
ERROR:  syntax error at or near "-"
LINE 1: listen my-channel;
```

**Comment by andywer** [comment]
Hey @overmike. That's more of a psql issue than a pg-listen one, but I think I can help you nevertheless.

You need to quote the identifier with backticks if it contains special characters. Try this:

```sql
LISTEN `my-channel`;
```

**Comment by overmike** [comment]
Thanks, didn't aware of it and thinking the oh listen module does not throw an error

**Comment by andywer** [comment]
No worries! Closing the issue.
