### ISSUE TITLE
Client has encountered a connection error and is not queryable

### ISSUE THREAD

**Issue by maxpain** [andywer/pg-listen#56]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/5875582/146438446-1bb67230-bec5-48a9-99c7-d6c839732e92.png">

By some reason `pg-listen` doesn't reconnect in some cases.

**Comment by andywer** [comment]
Thanks for sharing!

Hmm, might be an issue with `pg` itself, though. It's a bit nasty to debug and we would first need to find out if the unhandled promise rejection is caused by `pg-listen` or `pg`.

Can you share the exact version of `pg` that you are using, @maxpain?

**Comment by maxpain** [comment]
> Can you share the exact version of `pg` that you are using, @maxpain?

8.7.1

I also noticed that this is happening when PostgreSQL instance restarts.

This is log from our staging environment:
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/5875582/146508941-f628d5b0-a32e-4635-902d-fd7ace55e973.png">

**Comment by maxpain** [comment]
Any updates?

**Comment by maxpain** [comment]
I fixed this problem by setting `retryTimeout: Number.POSITIVE_INFINITY` in `pg-listen` options.
Why is it 3000 by default?
