### ISSUE TITLE
Default export could be improved

### ISSUE THREAD

**Issue by tahv0** [andywer/pg-listen#6]
Accessing "default" property is needed when coder imports module with `require`

`const createPostgresSubscriber = require('pg-listen').default`

This feels weird

**Comment by andywer** [comment]
Hey @tahv0. Thanks for the feedback :)

Added a small hack to make that possible (see [feature branch](https://github.com/andywer/pg-listen/tree/chore/commonjs-default-export)).

Give it a try by installing:

```sh
npm install pg-listen@experimental
```

Tell me if that works for you 😉

**Comment by tahv0** [comment]
Works fine, thanks! Could you merge that to your master and make new release?

Btw this module have very little tests. I would like to see few more. E.g:

1. hundreds or thousands new rows to db and see how this module handles those
2. Module promises reconnection and Error handling, I didn't see any tests for those
3. Tests for continuous health checks

**Comment by andywer** [comment]
Sure thing. You are right about the tests. Not sure when I will be able to tackle this, though. Can just tell you that I am running it in production already and at least right now it seems to work fine.

Would you mind creating a new issue for that?

**Comment by tahv0** [comment]
Ok, I'll do new Issue for that

**Comment by andywer** [comment]
Published as `v1.1.0`
